[phases.setup]
nixPkgs = ["php81", "nodejs", "mysql", "composer", "npm"]

[phases.build]
commands = [
  "composer install",
  "npm install",
  "npm run build",
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]